-- tch_features_v2_selected_candidate_pending.sql
--
-- Intentionally pending.
--
-- v2.5 should be created only after the v2.1/v2.2/v2.3/v2.4 ablations have
-- been trained and compared on validation/test zafras. It should not be a
-- blind "everything plus everything" dataset.
--
-- Suggested decision rule:
--   1. Start from public.tch_features_v2_core_optical_climate.
--   2. Add ENSO columns only if public.tch_features_v2_plus_enso improves
--      test performance without increasing train/test gap.
--   3. Add SAR columns only if public.tch_features_v2_plus_sar adds stable
--      signal beyond optical + climate.
--   4. Add CIRE columns only if public.tch_features_v2_plus_cire improves
--      validation/test, not only SHAP or train.
--   5. Add finca only if public.tch_features_v2_plus_finca improves temporal
--      generalization and does not behave like location memorization.
--
-- Placeholder template, to be edited after ablation results:
--
-- CREATE OR REPLACE VIEW public.tch_features_v2_selected_candidate AS
-- SELECT
--     core.*,
--     -- selected ENSO/SAR/CIRE/finca columns go here after evidence review
-- FROM public.tch_features_v2_core_optical_climate core
-- JOIN public.tch_features_v2_feature_bank base USING (cod_cg_zafra);
